using System.Text.Json.Serialization;

namespace MCPServer.Domain.Mcp;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false,
    GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
[JsonSerializable(typeof(InitializeRequest))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(McpImplementationInfo))]
[JsonSerializable(typeof(McpServerCapabilities))]
[JsonSerializable(typeof(McpToolsCapability))]
[JsonSerializable(typeof(McpLoggingCapability))]
[JsonSerializable(typeof(McpResourcesCapability))]
[JsonSerializable(typeof(McpPromptsCapability))]
[JsonSerializable(typeof(McpCompletionsCapability))]
[JsonSerializable(typeof(McpTasksCapability))]
[JsonSerializable(typeof(McpTaskRequestsCapability))]
[JsonSerializable(typeof(McpTask))]
[JsonSerializable(typeof(McpTask[]))]
[JsonSerializable(typeof(McpTaskMetadata))]
[JsonSerializable(typeof(McpRelatedTaskMetadata))]
[JsonSerializable(typeof(CreateTaskResult))]
[JsonSerializable(typeof(GetTaskRequest))]
[JsonSerializable(typeof(GetTaskResult))]
[JsonSerializable(typeof(GetTaskPayloadRequest))]
[JsonSerializable(typeof(ListTasksResult))]
[JsonSerializable(typeof(CancelTaskRequest))]
[JsonSerializable(typeof(CancelTaskResult))]
[JsonSerializable(typeof(TaskStatusNotificationParams))]
[JsonSerializable(typeof(CreateMessageRequestParams))]
[JsonSerializable(typeof(CreateMessageResult))]
[JsonSerializable(typeof(SamplingMessage))]
[JsonSerializable(typeof(SamplingMessage[]))]
[JsonSerializable(typeof(ModelPreferences))]
[JsonSerializable(typeof(ModelHint))]
[JsonSerializable(typeof(ModelHint[]))]
[JsonSerializable(typeof(ToolChoice))]
[JsonSerializable(typeof(ElicitRequestFormParams))]
[JsonSerializable(typeof(ElicitRequestUrlParams))]
[JsonSerializable(typeof(ElicitResult))]
[JsonSerializable(typeof(McpClientCapabilityState))]
[JsonSerializable(typeof(McpRoot))]
[JsonSerializable(typeof(McpRoot[]))]
[JsonSerializable(typeof(RootsListResult))]
[JsonSerializable(typeof(McpToolDescriptor))]
[JsonSerializable(typeof(McpIcon))]
[JsonSerializable(typeof(McpIcon[]))]
[JsonSerializable(typeof(McpToolExecution))]
[JsonSerializable(typeof(McpToolDescriptor[]))]
[JsonSerializable(typeof(ToolsListResult))]
[JsonSerializable(typeof(CursorRequestParams))]
[JsonSerializable(typeof(ToolsCallRequest))]
[JsonSerializable(typeof(ToolCallResult))]
[JsonSerializable(typeof(ToolContent))]
[JsonSerializable(typeof(TextToolContent))]
[JsonSerializable(typeof(ServerInfoStructuredContent))]
[JsonSerializable(typeof(McpResourceDescriptor))]
[JsonSerializable(typeof(McpResourceDescriptor[]))]
[JsonSerializable(typeof(ResourcesListResult))]
[JsonSerializable(typeof(ResourcesReadRequest))]
[JsonSerializable(typeof(ResourcesReadResult))]
[JsonSerializable(typeof(ResourceSubscriptionRequest))]
[JsonSerializable(typeof(ResourceUpdatedNotificationParams))]
[JsonSerializable(typeof(ResourceContent))]
[JsonSerializable(typeof(ResourceContent[]))]
[JsonSerializable(typeof(ResourceTemplatesListResult))]
[JsonSerializable(typeof(McpResourceTemplateDescriptor))]
[JsonSerializable(typeof(McpResourceTemplateDescriptor[]))]
[JsonSerializable(typeof(McpPromptDescriptor))]
[JsonSerializable(typeof(McpPromptDescriptor[]))]
[JsonSerializable(typeof(McpPromptArgument))]
[JsonSerializable(typeof(McpPromptArgument[]))]
[JsonSerializable(typeof(PromptsListResult))]
[JsonSerializable(typeof(PromptsGetRequest))]
[JsonSerializable(typeof(PromptsGetResult))]
[JsonSerializable(typeof(PromptMessage))]
[JsonSerializable(typeof(PromptMessage[]))]
[JsonSerializable(typeof(PromptContent))]
[JsonSerializable(typeof(TextPromptContent))]
[JsonSerializable(typeof(CompleteRequestParams))]
[JsonSerializable(typeof(CompletionArgument))]
[JsonSerializable(typeof(CompletionContext))]
[JsonSerializable(typeof(CompleteResult))]
[JsonSerializable(typeof(CompletionResultPayload))]
[JsonSerializable(typeof(CancelledNotificationParams))]
[JsonSerializable(typeof(ProgressNotificationParams))]
[JsonSerializable(typeof(LoggingSetLevelRequest))]
[JsonSerializable(typeof(LoggingMessageNotificationParams))]
[JsonSerializable(typeof(McpRequestMeta))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(System.Text.Json.JsonElement))]
public sealed partial class McpJsonSerializerContext : JsonSerializerContext
{
}
